require('lazy').setup({
  { 'tpope/vim-sleuth', event = 'BufReadPre' },

  require 'plugins.hop',
  require 'plugins.lazygit',
  require 'plugins.toggleterm',
  require 'plugins.gitsigns',
  require 'plugins.which-key',
  require 'plugins.telescope',
  require 'plugins.lspconfig',
  require 'plugins.conform',
  require 'plugins.cmp',
  require 'plugins.todo-comments',
  require 'plugins.mini',
  require 'plugins.treesitter',
  require 'plugins.neo-tree',
  require 'plugins.bufferline',
  require 'plugins.fzf',
  require 'plugins.rust',
  require 'plugins.catppuccin',
  require 'plugins.oil',
  require 'plugins.autopairs',
  require 'plugins.java',
  require 'plugins.snacks',
}, {
  ui = {
    icons = vim.g.have_nerd_font and {} or {
      cmd = '⌘',
      config = '🛠',
      event = '📅',
      ft = '📂',
      init = '⚙',
      keys = '🗝',
      plugin = '🔌',
      runtime = '💻',
      require = '🌙',
      source = '📄',
      start = '🚀',
      task = '📌',
      lazy = '💤 ',
    },
  },
})

-- vim: ts=2 sts=2 sw=2 et
